### PR TITLE
accepted solution (bad test case coverage though, like how would you even?)

### PR DESCRIPTION
**Pull request by SeanGrady**

### CODE REVIEW

**Comment by SeanGrady** [comment]
So, the way I've done the find_moves function seems objectively terrible, but I can't think of a better way to do it. I'd appreciate input if anyone has the time/inclination and has solved the thing or doesn't mind spoilers.

**Comment by SeanGrady** [comment]
also I have no idea how to test this properly. Google foobar tells me if I fail test cases but not what the test cases are, and it seems like you'd need to solve the problem to create tests to tell you if you've solved the problem.

**Comment by ryanloughlin25** [comment]
I don't mind reading your solution before I work on it, especially with an interview coming up.  I'll try to find some time today.  As for testing, two things come to mind right away.  You could write a brute force solution since the puzzle has a finite size and use it to produce tests for working on a better solution.  Or I think you can provide base cases and indirect tests by reasoning about the allowed operations.  

It should be straightforward that moving 4 spaces in a single direction is cheaper than moving 3 spaces in that direction because, in order to move in only a single direction overall, movement in the perpendicular direction must cancel out.  It's a strange test.  A failure would tell you that your code is not working, but it would not provide an example of what should happen.

**Comment by ryanloughlin25** [comment]
I think `find_moves` accepts a space as input and returns a list of the possible spaces you can move to?  If that's right, then I would:
• create a list of the possible abstract moves (i.e. two rows up and one column left, two rows up and one column right, two columns right and one row up, etc.).  There should be 8 of them.
• add the current space to each abstract move in the list to create a list of real moves
• filter out the real moves which would end up out of bounds to create and return a list of valid moves

**Comment by SeanGrady** [comment]
It does do that, and I agree with you, that's how I tried to write the function in the first place. What I ran into is I couldn't find a way to apply a transformation to a starting space that would result in a destination that is obviously invalid if out of range of the board. Right, like to go up and left, you take the starting space and subtract 8 and 8 and 1, for up one row, up one row and left one column. If the space is in the first two rows then this results in a negative number, which is obviously out of bounds. If it's not, though, but IS on the left side of the board, then it results in a valid number that is on the right side of the board, and I don't know how to easily algorithmically tell that you've wrapped around the board and so this isn't valid.

**Comment by ryanloughlin25** [comment]
all I can think of is to convert to/from row and column notation before/after creating the lists.

**Comment by SeanGrady** [comment]
Yeah, that occurred to me just now too. I think that probably is better, I'm gonna see if I can make it work.

**Pull request closed without merging**
